# Generated by Django 3.1.5 on 2021-01-31 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaginationDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
