# Generated by Django 3.1.5 on 2021-02-01 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sortnpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginationdemo',
            name='uuId',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='paginationdemo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
