# Generated by Django 3.1.7 on 2021-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortnpage', '0002_auto_20210201_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=127)),
                ('iteration', models.PositiveIntegerField(editable=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
