# Generated by Django 3.1.7 on 2021-03-28 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sortnpage', '0003_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginationdemo',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
