# Generated by Django 3.1.5 on 2021-02-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevelPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('access_level', models.PositiveIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
            ],
        ),
    ]
