# Generated by Django 3.1.5 on 2021-01-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='ChildB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedrelations.parent')),
            ],
        ),
        migrations.CreateModel(
            name='ChildA2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedrelations.childa')),
            ],
        ),
        migrations.CreateModel(
            name='ChildA1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedrelations.childa')),
            ],
        ),
        migrations.AddField(
            model_name='childa',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nestedrelations.parent'),
        ),
    ]
