# Generated by Django 3.1.5 on 2021-01-18 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nestedrelations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childa',
            name='dt',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='childa',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childAs', to='nestedrelations.parent'),
        ),
        migrations.AlterField(
            model_name='childa1',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childA1s', to='nestedrelations.childa'),
        ),
        migrations.AlterField(
            model_name='childa2',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childA2s', to='nestedrelations.childa'),
        ),
        migrations.AlterField(
            model_name='childb',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childBs', to='nestedrelations.parent'),
        ),
    ]
